# Extrinsics: chassis_camera_optical_frame -> top_camera_optical_frame
# P_chassis = R * P_top + T
# MATLAB Stereo Camera Calibrator, Camera1=Chassis, Camera2=Top

header:
  calibration_date: '2026-03-14'
  method: matlab_stereo_calibration
  source: MATLAB Stereo Camera Calibrator App

frame_id: chassis_camera_optical_frame
child_frame_id: top_camera_optical_frame

transform:
  translation:
    x: 0.0489497000000000
    y: -0.6105128215159799
    z: -0.4785342453116865
  rotation:
    x: -0.0778011163429091
    y: -0.0076294110014792
    z: 0.0133040893018528
    w: 0.9968509314794344
