      
header:
  calibration_date: 2025-08-27
  frame_id: rs16_lidar
child_frame_id: chassis_camera_optical_frame
transform:
  translation:
    x: 0.055
    y: 0.025
    z: 0.065
  rotation: 
    x: -0.509566
    y: 0.510878
    z: -0.483488
    w: 0.495566
