header:
  calibration_date: '2026-01-15'
  source: 'Computed: inv(arm_base → rslidar)'
  frame_id: rslidar
  child_frame_id: arm_base_link
transform:
  translation:
    x: -0.15454
    y: -0.00035292
    z: 0.0050000000000000044
  rotation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
