      
header:
  calibration_date: 2025-07-22
  frame_id: flan    #link6 end_pose
child_frame_id: hand_camera
transform:
  translation:
    x: -0.075
    y: 0.015
    z: 0.030
  rotation: 
    x: -0.107
    y: 0.106
    z: -0.700
    w: 0.698

